init:
    $ch1 = Character("CHAPTER ONE", who_size=33, callback=narrator_sprite_callback)
    $ch2 = Character("CHAPTER TWO", who_size=33, callback=narrator_sprite_callback)
    $ch3 = Character("CHAPTER THREE", who_size=33, callback=narrator_sprite_callback)
    $ch4 = Character("CHAPTER FOUR", who_size=33, callback=narrator_sprite_callback)
    $ch5 = Character("CHAPTER FIVE", who_size=33, callback=narrator_sprite_callback)
    $ch6 = Character("CHAPTER SIX", who_size=33, callback=narrator_sprite_callback)
    $ch7 = Character("CHAPTER SEVEN", who_size=33, callback=narrator_sprite_callback)
    $ch8 = Character("CHAPTER EIGHT", who_size=33, callback=narrator_sprite_callback)
    $ch9 = Character("CHAPTER NINE", who_size=33, callback=narrator_sprite_callback)
    $ch10 = Character("CHAPTER TEN", who_size=33, callback=narrator_sprite_callback)
    $ch11 = Character("CHAPTER ELEVEN", who_size=33, callback=narrator_sprite_callback)
    $ch12 = Character("CHAPTER TWELVE", who_size=33, callback=narrator_sprite_callback)
    $ch13 = Character("CHAPTER THIRTEEN", who_size=33, callback=narrator_sprite_callback)
    $ch14 = Character("CHAPTER FOURTEEN", who_size=33, callback=narrator_sprite_callback)
    $ch15 = Character("CHAPTER FIFTEEN", who_size=33, callback=narrator_sprite_callback)
    $ch16 = Character("CHAPTER SIXTEEN", who_size=33, callback=narrator_sprite_callback)
    $ch17 = Character("CHAPTER SEVENTEEN", who_size=33, callback=narrator_sprite_callback)
    $ch18 = Character("CHAPTER EIGHTEEN", who_size=33, callback=narrator_sprite_callback)
    $ch19 = Character("CHAPTER NINETEEN", who_size=33, callback=narrator_sprite_callback)
    $ch20 = Character("CHAPTER TWENTY", who_size=33, callback=narrator_sprite_callback)
    $ch21 = Character("CHAPTER TWENTY-ONE", who_size=33, callback=narrator_sprite_callback)
    $epilogue = Character("EPILOGUE", who_size=33, callback=narrator_sprite_callback)
